### ISSUE TITLE
Taxonomy Menu rebuild process encountered an error - version 1.x-1.53

### ISSUE THREAD

**Issue by jvillacriz** [backdrop-contrib/taxonomy_menu#11] opened 2023-08-22 21:41 UTC
There is an error in version 1.x-1.53
![image](https://github.com/backdrop-contrib/taxonomy_menu/assets/68474819/7f7204b1-48b2-493c-a3ff-71cc5216f321)

![image](https://github.com/backdrop-contrib/taxonomy_menu/assets/68474819/00caa335-f1dc-4e5a-988d-48c4a443cb47)

As a result, the taxonomy menu cannot be displayed in the default layout.

But version 1.x-1.52 works fine.

**Comment by Wylbur** [comment] 2023-12-03 20:23
I'm also getting this error when I install Taxonomy menu from scratch.  This is the error that is generated when I try to save a taxonomy term:
```
Too few arguments to function taxonomy_menu_handler(), 2 passed in /home/twincitiesamnest/ai37/web/modules/taxonomy_menu/taxonomy_menu.module on line 458 and at least 3 expected
```

During the install, the same errors as in comment one, and the errors below when trying to save changes to any items in a vocabulary assigned to a taxonomy menu. 

This is the module unusable.

**Comment by jvillacriz** [comment] 2023-12-04 03:12
Try version 1.x-1.52

**Comment by albanycomputers** [comment] 2024-02-12 14:18
Same problem here... tried with php8 and other issues...  1.5.2 works for me.

**Comment by eric2pin** [comment] 2024-06-03 14:21
Same problem, module throws fatal error when enabled on a taxonomy / while trying to generate the links. I submitted a pull request that's fixing the issue for me.

**Comment by nattywebdev** [comment] 2024-08-29 10:27
I applied the same fix as referred to by @eric2pin - it fixed this issue for me too, except my two-level taxonomy vocab is flattened into one level in the menu.

**Comment by argiepiano** [comment] 2024-08-29 12:48
I can confirm @nattywebdev's decribed behavior after adding @eric2pin's fix. When rebuilding the menus, all levels are flattened.

**Comment by argiepiano** [comment] 2024-08-29 15:56
@nattywebdev I've opened a new issue for this flattened menu problem. #13.

I'll provide a PR in a few minutes. Can you please test?

**Comment by nattywebdev** [comment] 2024-08-29 16:03
Sure can - let me know when it's ready.

**Comment by argiepiano** [comment] 2024-08-29 16:10
I've submitted a more comprehensive PR that fixes this problem and also the term hierarchy issue #13. You may want to close this PR.

**Comment by argiepiano** [comment] 2024-08-29 16:10
@nattywebdev to test, please patch the dev version with PR #14

**Comment by argiepiano** [comment] 2024-08-29 16:12
@nattywebdev to test, you will need to:
1. Use the dev version (1.x-1.x), not the latest
2. REVERT PR #12 if you applied it before. The PR #14 actually also fixes that
3. Apply PR #14

**Comment by nattywebdev** [comment] 2024-08-29 16:27
Thanks for that info. I had uninstalled the taxonomy menu module as I didn't appreciate there would be this quick a fix, so applying #14 should be straightforward. I'll feed back shortly.

**Comment by nattywebdev** [comment] 2024-08-29 16:49
Re-installed, manually patched and linked to a menu and I can confirm my two-level taxonomy is replicated correctly in the menu.
Thank you so much!

**Comment by jenlampton** [comment] 2024-10-19 02:30
https://github.com/backdrop-contrib/taxonomy_menu/pull/14 has been merged, which also fixes this.

**Closed as completed by jenlampton** 2024-10-19 02:30 UTC
